CREATE TABLE try_out1(
Id	INT IDENTITY(1,1)	NOT NULL
,Name	NVARCHAR(100)	NOT NULL
,Email	NVARCHAR(100)	NOT NULL
,Password	NVARCHAR(60)	NOT NULL
,created_by	INT	NULL
,created_date	DATETIMEOFFSET	NULL
,updated_by	INT	NULL
,updated_date	DATETIMEOFFSET	NULL)