CREATE TABLE client_contracts(
client_contract_id	INT IDENTITY(1,1)	NOT NULL
,client_id	INT	NULL
,contract_no	NVARCHAR(100)	NULL
,contract_date	DATE	NULL
,contract_term_id	INT	NULL
,activation_date	DATE	NULL
,expiry_date	DATE	NULL
,plan_id	INT	NULL
,plan_qty	INT	NULL
,srp_amount	DECIMAL(12)	NULL
,dp_amount	DECIMAL(12)	NULL
,less_dp_amount	DECIMAL(12)	NULL
,total_amort_amount	DECIMAL(12)	NULL
,monthly_amort_amount	DECIMAL(12)	NULL
,is_active	CHAR(1)	NULL
,created_by	INT	NULL
,created_date	DATE	NULL
,updated_by	INT	NULL
,updated_date	DATE	NULL)