CREATE TABLE client_contracts(
client_contract_id	INT IDENTITY(1,1)	NOT NULL
,client_id	INT	NULL
,contract_no	NVARCHAR(100)	NULL
,contract_date	DATE	NULL
,contract_term_id	INT	NULL
,activation_date	DATE	NULL
,expiry_date	DATE	NULL
,plan_id	INT	NULL
,plan_qty	INT	NULL
,device_model_id	INT	NULL
,device_qty	INT	NULL
,device_term_id	INT	NULL
,unit_assignment_type_id	INT	NULL
,is_active	CHAR(1)	NULL
,created_by	INT	NULL
,created_date	DATE	NULL
,updated_by	INT	NULL
,updated_date	DATE	NULL)