CREATE TABLE dtr_details(
dtr_dtl_id	INT IDENTITY(1,1)	NOT NULL
,dtr_hdr_id	INT	NULL
,dtr_date	DATE	NULL
,time_in	TIME(32)	NULL
,time_out	TIME(32)	NULL
,act_hours	DECIMAL(7)	NULL
,tardiness_hours	DECIMAL(7)	NULL
,ot_hours	DECIMAL(7)	NULL
,np_hours	DECIMAL(7)	NULL
,sl_wp_hours	DECIMAL(7)	NULL
,sl_wop_hours	DECIMAL(7)	NULL
,vl_wp_hours	DECIMAL(7)	NULL
,vl_wop_hours	DECIMAL(7)	NULL
,el_wp_hours	DECIMAL(7)	NULL
,el_wop_hours	DECIMAL(7)	NULL
,created_by	INT	NULL
,created_date	DATETIME	NULL
,updated_by	INT	NULL
,updated_date	DATETIME	NULL)