CREATE TABLE tax_computation_ref(
tax_except_id	INT IDENTITY(1,1)	NOT NULL
,tax_except_code	CHAR(5)	NULL
,excemption_amount	DECIMAL(12)	NULL
,col1_less_amount	DECIMAL(12)	NULL
,col1_tax_amount	DECIMAL(12)	NULL
,col1_pct	INT	NULL
,col2_less_amount	DECIMAL(12)	NULL
,col2_tax_amount	DECIMAL(12)	NULL
,col2_pct	INT	NULL
,col3_less_amount	DECIMAL(12)	NULL
,col3_tax_amount	DECIMAL(12)	NULL
,col3_pct	INT	NULL
,col4_less_amount	DECIMAL(12)	NULL
,col4_tax_amount	DECIMAL(12)	NULL
,col4_pct	INT	NULL
,col5_less_amount	DECIMAL(12)	NULL
,col5_tax_amount	DECIMAL(12)	NULL
,col5_pct	INT	NULL
,col6_less_amount	DECIMAL(12)	NULL
,col6_tax_amount	DECIMAL(12)	NULL
,col6_pct	INT	NULL
,col7_less_amount	DECIMAL(12)	NULL
,col7_tax_amount	DECIMAL(12)	NULL
,col7_pct	INT	NULL
,col8_less_amount	DECIMAL(12)	NULL
,col8_tax_amount	DECIMAL(12)	NULL
,col8_pct	INT	NULL
,created_by	INT	NULL
,created_date	DATETIME	NULL
,updated_by	INT	NULL
,updated_date	DATETIME	NULL)